// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

type UseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCase) EXPECT() *UseCase_Expecter {
	return &UseCase_Expecter{mock: &_m.Mock}
}

// NewChat provides a mock function with given fields: ctx, id
func (_m *UseCase) NewChat(ctx context.Context, id int64) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for NewChat")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UseCase_NewChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewChat'
type UseCase_NewChat_Call struct {
	*mock.Call
}

// NewChat is a helper method to define mock.On call
//   - ctx context.Context
//   - id int64
func (_e *UseCase_Expecter) NewChat(ctx interface{}, id interface{}) *UseCase_NewChat_Call {
	return &UseCase_NewChat_Call{Call: _e.mock.On("NewChat", ctx, id)}
}

func (_c *UseCase_NewChat_Call) Run(run func(ctx context.Context, id int64)) *UseCase_NewChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(int64))
	})
	return _c
}

func (_c *UseCase_NewChat_Call) Return(_a0 error) *UseCase_NewChat_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UseCase_NewChat_Call) RunAndReturn(run func(context.Context, int64) error) *UseCase_NewChat_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
