global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'scraper'
    metrics_path: /metrics
    static_configs:
      - targets: ['scrapper:9100']
  - job_name: 'bot'
    static_configs:
      - targets: ['bot:9200']
