// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	bot "bot/internal/model/bot"
	mock "github.com/stretchr/testify/mock"
)

// UseCase is an autogenerated mock type for the UseCase type
type UseCase struct {
	mock.Mock
}

type UseCase_Expecter struct {
	mock *mock.Mock
}

func (_m *UseCase) EXPECT() *UseCase_Expecter {
	return &UseCase_Expecter{mock: &_m.Mock}
}

// Update provides a mock function with given fields: linkUpdate
func (_m *UseCase) Update(linkUpdate *bot.LinkUpdate) error {
	ret := _m.Called(linkUpdate)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*bot.LinkUpdate) error); ok {
		r0 = rf(linkUpdate)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UseCase_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type UseCase_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - linkUpdate *bot.LinkUpdate
func (_e *UseCase_Expecter) Update(linkUpdate interface{}) *UseCase_Update_Call {
	return &UseCase_Update_Call{Call: _e.mock.On("Update", linkUpdate)}
}

func (_c *UseCase_Update_Call) Run(run func(linkUpdate *bot.LinkUpdate)) *UseCase_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*bot.LinkUpdate))
	})
	return _c
}

func (_c *UseCase_Update_Call) Return(_a0 error) *UseCase_Update_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *UseCase_Update_Call) RunAndReturn(run func(*bot.LinkUpdate) error) *UseCase_Update_Call {
	_c.Call.Return(run)
	return _c
}

// NewUseCase creates a new instance of UseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *UseCase {
	mock := &UseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
